// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJXF5Pa4ZutiIsHCH8fBl1KCjz37WCB8M',
    appId: '1:422534235808:web:0f29fc93710e9368caabc5',
    messagingSenderId: '422534235808',
    projectId: 'eras-7946a',
    authDomain: 'eras-7946a.firebaseapp.com',
    storageBucket: 'eras-7946a.firebasestorage.app',
    measurementId: 'G-X181YTJVBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPx0yiNMLBeCHcgcaYWq2_z7ECgazmGW8',
    appId: '1:422534235808:android:c7ade5b4f2e77f5acaabc5',
    messagingSenderId: '422534235808',
    projectId: 'eras-7946a',
    storageBucket: 'eras-7946a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8A8PH4RCeHSvK6KYfrgmT1z6WVBS9h80',
    appId: '1:422534235808:ios:592b305f3082417acaabc5',
    messagingSenderId: '422534235808',
    projectId: 'eras-7946a',
    storageBucket: 'eras-7946a.firebasestorage.app',
    iosBundleId: 'com.example.eras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8A8PH4RCeHSvK6KYfrgmT1z6WVBS9h80',
    appId: '1:422534235808:ios:592b305f3082417acaabc5',
    messagingSenderId: '422534235808',
    projectId: 'eras-7946a',
    storageBucket: 'eras-7946a.firebasestorage.app',
    iosBundleId: 'com.example.eras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJXF5Pa4ZutiIsHCH8fBl1KCjz37WCB8M',
    appId: '1:422534235808:web:b6ccee1253bd3ed8caabc5',
    messagingSenderId: '422534235808',
    projectId: 'eras-7946a',
    authDomain: 'eras-7946a.firebaseapp.com',
    storageBucket: 'eras-7946a.firebasestorage.app',
    measurementId: 'G-GQ0EWS22VR',
  );

}