import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Supported languages in ERAS.
enum AppLanguage {
  english('English', 'en'),
  hausa('Hausa', 'ha'),
  fulani('Fulfulde', 'ff'),
  igbo('Igbo', 'ig'),
  yoruba('Yoruba', 'yo');

  const AppLanguage(this.label, this.code);
  final String label;
  final String code;
}

/// Current language state.
final appLanguageProvider = StateProvider<AppLanguage>((ref) => AppLanguage.english);

/// Get a translated string by key.
String tr(WidgetRef ref, String key) {
  final lang = ref.watch(appLanguageProvider);
  return _translations[lang]?[key] ?? _translations[AppLanguage.english]?[key] ?? key;
}

/// Non-widget version for callbacks.
String trRead(Ref ref, String key) {
  final lang = ref.read(appLanguageProvider);
  return _translations[lang]?[key] ?? _translations[AppLanguage.english]?[key] ?? key;
}

/// Static lookup (for use outside of providers).
String trStatic(AppLanguage lang, String key) {
  return _translations[lang]?[key] ?? _translations[AppLanguage.english]?[key] ?? key;
}

/// All translations.
const Map<AppLanguage, Map<String, String>> _translations = {
  // ─── ENGLISH ───────────────────────────────────────────────
  AppLanguage.english: {
    // Login
    'app_name': 'ERAS',
    'app_subtitle': 'Emergency Response Alert System',
    'email': 'Email',
    'password': 'Password',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'no_account': "Don't have an account?",
    'have_account': 'Already have an account?',
    'or': 'OR',
    'demo_mode': 'Enter Demo Mode',
    'demo_subtitle': 'Preview all screens with sample data',
    'email_required': 'Email is required',
    'email_invalid': 'Enter a valid email',
    'password_required': 'Password is required',
    'password_short': 'Password must be 6+ characters',
    'full_name': 'Full Name',
    'phone': 'Phone Number',
    'name_required': 'Name is required',
    'select_role': 'Select Your Role',
    'language': 'Language',

    // Role Selection
    'hello': 'Hello',
    'how_use': 'How would you like to use ERAS today?',
    'need_help': 'I Need Help',
    'need_help_sub': 'Trigger an SOS emergency alert\nto nearby responders',
    'can_help': 'I Can Help',
    'can_help_sub': 'View incoming alerts and\nrespond to emergencies',
    'medical_profile': 'Medical Profile',
    'sign_out': 'Sign Out',
    'demo_badge': 'Demo Mode - No Firebase Required',

    // Victim
    'press_sos': 'Press SOS for help',
    'alert_sent_immediately': 'Alert is sent IMMEDIATELY\nthen you select emergency type',
    'gps_active': 'GPS Active \u2022 Ready',
    'call_112': 'Call 112',
    'call_nema': 'Call NEMA',
    'ambulance': 'Ambulance',
    'demo_sos_sent': 'Demo: SOS Alert sent! Searching for responders...',

    // Emergency Type
    'emergency_type': 'Emergency Type',
    'alert_sent_banner': 'ALERT SENT - Searching for responders',
    'select_type_guidance': 'Select emergency type below for specific first aid guidance',
    'what_emergency': 'What kind of emergency?',
    'confirm_continue': 'CONFIRM & CONTINUE',
    'select_emergency_type': 'SELECT EMERGENCY TYPE',
    'first_aid_follow': 'Follow these steps while waiting for a responder:',
    'responder_on_way': 'A responder is on the way. Stay calm and follow the steps above.',

    // Waiting
    'help_on_way': 'Help is on the way!',
    'searching_responders': 'Searching for nearby responders...',
    'location_shared': 'Your location has been shared',
    'stay_calm': 'Stay calm. A trained responder is being dispatched to your location. Keep your phone accessible.',
    'call_also': 'You can also call 112 (Emergency) or 199 (Ambulance)',
    'cancel': 'Cancel',
    'first_aid': 'First Aid',
    'first_aid_steps': 'Follow these steps while help is arriving:',

    // Responder
    'responder': 'Responder',
    'active': 'ACTIVE',
    'offline': 'OFFLINE',
    'incoming_alerts': 'Incoming Alerts',
    'you_offline': 'You are offline',
    'toggle_active': 'Toggle Active to start receiving emergency alerts',
    'no_alerts': 'No active alerts',
    'waiting_emergencies': "You're online - waiting for nearby emergencies",
    'demo_alerts_label': 'DEMO MODE - These are simulated alerts for preview',
    'responses': 'Responses',
    'rating': 'Rating',
    'status': 'Status',
    'accept': 'Accept',
    'decline': 'Decline',
    'accepting': 'Accepting...',
    'arrived': "I've Arrived",

    // Emergency types
    'cardiac': 'Cardiac',
    'trauma': 'Trauma',
    'respiratory': 'Respiratory',
    'burn': 'Burn',
    'choking': 'Choking',
    'other': 'Other',

    // Registration
    'create_account': 'Create Account',
    'get_help': 'Get Help',
    'get_help_sub': 'I need emergency assistance',
    'help_others': 'Help Others',
    'help_others_sub': 'I am a medical professional / first aider',
    'both': 'Both',
    'both_sub': 'I want both capabilities',
    'sign_in_link': 'Sign In',
  },

  // ─── HAUSA ─────────────────────────────────────────────────
  AppLanguage.hausa: {
    'app_name': 'ERAS',
    'app_subtitle': 'Tsarin Sanarwar Gaggawa',
    'email': 'Imel',
    'password': 'Kalmar sirri',
    'sign_in': 'Shiga',
    'sign_up': 'Yi rajista',
    'no_account': 'Ba ku da asusu?',
    'have_account': 'Kuna da asusu?',
    'or': 'KO',
    'demo_mode': 'Shiga Gwaji',
    'demo_subtitle': 'Duba duk allon tare da bayanan gwaji',
    'email_required': 'Ana bukatar imel',
    'email_invalid': 'Shigar da ingantaccen imel',
    'password_required': 'Ana bukatar kalmar sirri',
    'password_short': 'Kalmar sirri dole ta kai 6+',
    'full_name': 'Cikakken suna',
    'phone': 'Lambar waya',
    'name_required': 'Ana bukatar suna',
    'select_role': 'Zabi matsayinka',
    'language': 'Harshe',
    'hello': 'Sannu',
    'how_use': 'Yaya kuke son amfani da ERAS yau?',
    'need_help': 'Ina bukatar taimako',
    'need_help_sub': 'Aika sanarwar gaggawa\nzuwa ga masu amsa kusa',
    'can_help': 'Zan iya taimakawa',
    'can_help_sub': 'Duba sanarwar gaggawa\nkuma amsa su',
    'medical_profile': 'Bayanan Lafiya',
    'sign_out': 'Fita',
    'demo_badge': 'Yanayin Gwaji - Ba a bukatar Firebase',
    'press_sos': 'Danna SOS don taimako',
    'alert_sent_immediately': 'Ana aika sanarwa NAN DA NAN\nsa\'an nan ka zabi nau\'in gaggawa',
    'gps_active': 'GPS yana aiki \u2022 A shirye',
    'call_112': 'Kira 112',
    'call_nema': 'Kira NEMA',
    'ambulance': 'Motar Asibiti',
    'emergency_type': 'Nau\'in Gaggawa',
    'alert_sent_banner': 'AN AIKA SANARWA - Ana neman masu amsa',
    'select_type_guidance': 'Zabi nau\'in gaggawa don samun jagorar agajin farko',
    'what_emergency': 'Wane irin gaggawa ce?',
    'confirm_continue': 'TABBATAR & CI GABA',
    'select_emergency_type': 'ZABI NAU\'IN GAGGAWA',
    'help_on_way': 'Taimako yana zuwa!',
    'searching_responders': 'Ana neman masu amsa kusa...',
    'location_shared': 'An raba wurin ku',
    'stay_calm': 'Ku kwantar da hankali. Ana aika mai amsa zuwa wurin ku.',
    'cancel': 'Soke',
    'responder': 'Mai Amsa',
    'active': 'YA KUNNA',
    'offline': 'A KASHE',
    'incoming_alerts': 'Sanarwar da ke shigowa',
    'you_offline': 'Ba ku kan layi ba',
    'toggle_active': 'Kunna don fara karbar sanarwar gaggawa',
    'accept': 'Karba',
    'decline': 'Ki',
    'arrived': 'Na iso',
    'cardiac': 'Zuciya',
    'trauma': 'Rauni',
    'respiratory': 'Numfashi',
    'burn': 'Konewa',
    'choking': 'Shakar abu',
    'other': 'Wani',
    'create_account': 'Bude asusu',
    'get_help': 'Nemi taimako',
    'get_help_sub': 'Ina bukatar taimakon gaggawa',
    'help_others': 'Taimaki wasu',
    'help_others_sub': 'Ni likita ne / mai agajin farko',
    'both': 'Duka biyun',
    'both_sub': 'Ina son duka biyun',
    'sign_in_link': 'Shiga',
    'responses': 'Amsoshi',
    'rating': 'Kima',
    'status': 'Matsayi',
  },

  // ─── FULFULDE (FULANI) ─────────────────────────────────────
  AppLanguage.fulani: {
    'app_name': 'ERAS',
    'app_subtitle': 'Yuɓɓo Ɗemngal Kisal',
    'email': 'Imel',
    'password': 'Finnde',
    'sign_in': 'Naatu',
    'sign_up': 'Winndito',
    'no_account': 'A walaa konte?',
    'have_account': 'A heɓii konte?',
    'or': 'WALLA',
    'demo_mode': 'Naatu e nder hollirgol',
    'demo_subtitle': 'Hollu kala hello e keɓe jarribugol',
    'language': 'Ɗemngal',
    'hello': 'A jaraama',
    'how_use': 'Hol no njiɗ-ɗaa huutoraade ERAS hannde?',
    'need_help': 'Mi haaji ballal',
    'need_help_sub': 'Neldu ɗemngal kisal\ne wallitooji ɓadiiɓe',
    'can_help': 'Mi waawi wallude',
    'can_help_sub': 'Yiy ɗemgule kisal\nnde njaaboto-ɗaa',
    'medical_profile': 'Humpito cellal',
    'sign_out': 'Yaltu',
    'press_sos': 'Ñoƴƴu SOS ngam ballal',
    'help_on_way': 'Ballal ana e laawol!',
    'cancel': 'Haaytu',
    'responder': 'Jaaboowo',
    'active': 'WONI E DOW',
    'offline': 'WONI E LES',
    'accept': 'Jaɓ',
    'decline': 'Salo',
    'arrived': 'Mi yottii',
    'cardiac': 'Ɓernde',
    'trauma': 'Gaañe',
    'respiratory': 'Foofaandu',
    'burn': 'Wulnde',
    'choking': 'Ƴogaade',
    'other': 'Goɗɗum',
    'create_account': 'Uddit konte',
    'sign_in_link': 'Naatu',
  },

  // ─── IGBO ──────────────────────────────────────────────────
  AppLanguage.igbo: {
    'app_name': 'ERAS',
    'app_subtitle': 'Usoro Mkpọsa Ọnọdụ Mberede',
    'email': 'Email',
    'password': 'Okwuntụghe',
    'sign_in': 'Banye',
    'sign_up': 'Debanye aha',
    'no_account': 'I nweghị akaụntụ?',
    'have_account': 'I nwere akaụntụ?',
    'or': 'MA',
    'demo_mode': 'Banye nnwale',
    'demo_subtitle': 'Hụ ihuenyo niile na data nnwale',
    'language': 'Asụsụ',
    'hello': 'Nnọọ',
    'how_use': 'Kedu ka ị ga-esi jiri ERAS taa?',
    'need_help': 'Achọrọ m enyemaka',
    'need_help_sub': 'Zipụ mkpọsa mberede\nnye ndị na-enyere aka nọ nso',
    'can_help': 'Enwere m ike inyere aka',
    'can_help_sub': 'Hụ mkpọsa mberede\nma zaghachi ha',
    'medical_profile': 'Profaịlụ ahụike',
    'sign_out': 'Pụọ',
    'press_sos': 'Pịa SOS maka enyemaka',
    'help_on_way': 'Enyemaka na-abịa!',
    'cancel': 'Kagbuo',
    'responder': 'Onye nzaghachi',
    'active': 'N\'ARỤ ỌRỤ',
    'offline': 'APỤỌ',
    'accept': 'Nabata',
    'decline': 'Jụ',
    'arrived': 'Abịara m',
    'cardiac': 'Obi',
    'trauma': 'Mmerụ ahụ',
    'respiratory': 'Iku ume',
    'burn': 'Ọkụ gbara',
    'choking': 'Mgbachi',
    'other': 'Nke ọzọ',
    'create_account': 'Mepee akaụntụ',
    'sign_in_link': 'Banye',
    'emergency_type': 'Ụdị mberede',
    'what_emergency': 'Kedu ụdị mberede?',
    'confirm_continue': 'KWADO & GA N\'IHU',
    'select_emergency_type': 'HỌRỌ ỤDỊ MBEREDE',
    'searching_responders': 'Na-achọ ndị nzaghachi nọ nso...',
    'incoming_alerts': 'Mkpọsa na-abata',
    'responses': 'Nzaghachi',
    'rating': 'Ọkwa',
    'status': 'Ọnọdụ',
  },

  // ─── YORUBA ────────────────────────────────────────────────
  AppLanguage.yoruba: {
    'app_name': 'ERAS',
    'app_subtitle': 'Eto Ikilo Idahun Pajawiri',
    'email': 'Imeeli',
    'password': 'Ọrọ igbaniwọle',
    'sign_in': 'Wọle',
    'sign_up': 'Forukọsilẹ',
    'no_account': 'O ko ni akọọlẹ?',
    'have_account': 'O ti ni akọọlẹ?',
    'or': 'TABI',
    'demo_mode': 'Wọ ipo idanwo',
    'demo_subtitle': 'Wo gbogbo oju-iwe pẹlu data idanwo',
    'language': 'Ede',
    'hello': 'Ẹ kú àárọ',
    'how_use': 'Bawo ni o ṣe fẹ lo ERAS loni?',
    'need_help': 'Mo nilo iranlọwọ',
    'need_help_sub': 'Fi ikilo pajawiri ranṣẹ\nsi awọn oluyọnda nitosi',
    'can_help': 'Mo le ran lọwọ',
    'can_help_sub': 'Wo awọn ikilo pajawiri\nki o si dahun wọn',
    'medical_profile': 'Profaili ilera',
    'sign_out': 'Jade',
    'press_sos': 'Tẹ SOS fun iranlọwọ',
    'help_on_way': 'Iranlọwọ wa lona!',
    'cancel': 'Fagilee',
    'responder': 'Oludahun',
    'active': 'N ṢIṢẸ',
    'offline': 'KO SI LORI AYELUJARA',
    'accept': 'Gba',
    'decline': 'Kọ',
    'arrived': 'Mo ti de',
    'cardiac': 'Ọkan',
    'trauma': 'Ipalara',
    'respiratory': 'Mimi',
    'burn': 'Ijona',
    'choking': 'Fifun',
    'other': 'Miran',
    'create_account': 'Ṣii akọọlẹ',
    'sign_in_link': 'Wọle',
    'emergency_type': 'Iru pajawiri',
    'what_emergency': 'Iru pajawiri wo ni?',
    'confirm_continue': 'JẸRISI & TẸSIWAJU',
    'select_emergency_type': 'YAN IRU PAJAWIRI',
    'searching_responders': 'A n wa awọn oludahun nitosi...',
    'incoming_alerts': 'Awọn ikilo ti n wọle',
    'responses': 'Idahun',
    'rating': 'Igbelewọn',
    'status': 'Ipo',
    'alert_sent_banner': 'IKILO TI RANṢẸ - A n wa awọn oludahun',
    'location_shared': 'A ti pin ipo rẹ',
    'stay_calm': 'Balẹ. A n ranṣẹ oludahun si ipo rẹ.',
  },
};
